### ISSUE TITLE
It does not return JSON obeject

### ISSUE THREAD

**Issue by osamasado** [viralvaghela/flutter_insta#16]
<!DOCTYPE html>
I/flutter (18403): <html lang="en" class="no-js not-logged-in client-root">
I/flutter (18403):     <head>
I/flutter (18403):         <meta charset="utf-8">
I/flutter (18403):         <meta http-equiv="X-UA-Compatible" content="IE=edge">
I/flutter (18403): 
I/flutter (18403):         <title>
I/flutter (18403): Login • Instagram
I/flutter (18403): </title>
I/flutter (18403): 
I/flutter (18403):         
I/flutter (18403):         <meta name="robots" content="noimageindex, noarchive">
I/flutter (18403):         <meta name="apple-mobile-web-app-status-bar-style" content="default">
I/flutter (18403):         <meta name="mobile-web-app-capable" content="yes">
I/flutter (18403):         <meta name="theme-color" content="#ffffff">
I/flutter (18403):         <meta id="viewport" name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1, viewport-fit=cover">
I/flutter (18403):         <link rel="manifest" href="/data/manifest.json">
I/flutter (18403): 
I/flutter (18403):         <link rel="preload" href="/static/bundles/metro/ConsumerUICommons.css/5427b1b6bf3f.css" as="style" type="text/css" crossorigin="anonymous" />
I/flutter (18403): <link rel="preload" href="/static/bundles/metro/Consumer.css/12cbbeb252d9.css" as="style" type="text/css" crossorigin="anonymous" />
I/flutter (18403): <link rel="preload" href="/static/bundles/metro/FBSi
E/flutter (18403): [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: FormatException: Unexpected character (at character 1)
E/flutter (18403): <!DOCTYPE html>

**Comment by DavideM12** [comment]
Hi omasado,

it's the same thing of this thread:
https://github.com/viralvaghela/flutter_insta/issues/13

It's due to Facebook's API limit. We should integrate this package with oEmbed API.
