### ISSUE TITLE
FormatException (FormatException: Unexpected character (at character 1) <!DOCTYPE html> ^ )

### ISSUE THREAD

**Issue by nabilkrs** [viralvaghela/flutter_insta#20]
I'm working on a Flutter app and I'm using flutter_insta package. The call of the method getProfileData() cause this error please I need help.

**Comment by DavideM12** [comment]
#13

**Comment by nabilkrs** [comment]
solved
-------------------
I solved this issue by completing the development process without running on the emulator or real device because Instagram gives you a few requests per hour while the hot reload makes thousands of requests with each reload. I released the app as apk and installed it on my own phone and everything is ok.

**Comment by nabilkrs** [comment]
**solved**
----------------------------
I solved this issue by completing the development process without running on the emulator or real device because Instagram gives you a few requests per hour while the hot reload makes a huge amount of requests with each reload. I released the app as apk and installed it on my own phone and everything is ok.
