### ISSUE TITLE
Need To Login Problem

### ISSUE THREAD

**Issue by OS-Sado** [viralvaghela/flutter_insta#22]
Ich have problem after anumber of calling this API, that I need to login, can you help me to solve this problem?
Here is the response of calling await flutterInsta.getProfileData("my_account");
`I/flutter (17374): <!DOCTYPE html>
I/flutter (17374): <html lang="en" class="no-js not-logged-in client-root">
I/flutter (17374):     <head>
I/flutter (17374):         <meta charset="utf-8">
I/flutter (17374):         <meta http-equiv="X-UA-Compatible" content="IE=edge">
I/flutter (17374): 
I/flutter (17374):         <title>
I/flutter (17374): Login • Instagram
I/flutter (17374): </title>
I/flutter (17374): 
I/flutter (17374):         
I/flutter (17374):         <meta name="robots" content="noimageindex, noarchive">
I/flutter (17374):         <meta name="apple-mobile-web-app-status-bar-style" content="default">
I/flutter (17374):         <meta name="mobile-web-app-capable" content="yes">
I/flutter (17374):         <meta name="theme-color" content="#ffffff">
I/flutter (17374):         <meta id="viewport" name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1, viewport-fit=cover">
I/flutter (17374):         <link rel="manifest" href="/data/manifest.json">
I/flutter (17374): 
I/flutter (17374):         <link rel="preload" href="/static/bundles/metro/ConsumerUICommons.css/491667cd4d19.css" as="style" type="text/css" crossorigin="anonymous" />
I/flutter (17374): <link rel="preload" href="/static/bundles/metro/Consumer.css/cda6a893226a.css" as="style" type="text/css" crossorigin="anonymous" />
I/flutter (17374): <link rel="preload" href="/static/bundles/metro/FBSi
E/flutter (17374): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: FormatException: Unexpected character (at character 1)
E/flutter (17374): <!DOCTYPE html>`

**Comment by thakkarsweta** [comment]
Any solution in this ?

**Comment by MdSaifUddin** [comment]
Any update?

**Comment by ravindravala** [comment]
@swetaVanjara @MdSaifUddin  check [this](https://github.com/ravindravala/Flutter-Reels-downloader-for-instagram)

**Comment by viralvaghela** [comment]
Hello @swetaVanjara @MdSaifUddin @OS-Sado @ravindravala  Issue has been fixed and updated the package. Now it's working fine!
