### ISSUE TITLE
Unhandled Exception: FormatException: Unexpected character (at character 1)

### ISSUE THREAD

**Issue by deveshgarg-max** [viralvaghela/flutter_insta#4]
[ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: FormatException: Unexpected character (at character 1)
E/flutter (14133): <!DOCTYPE html>
E/flutter (14133): ^
E/flutter (14133):
E/flutter (14133): #0      _ChunkedJsonParser.fail  (dart:convert-patch/convert_patch.dart:1394:5)
E/flutter (14133): #1      _ChunkedJsonParser.parseNumber  (dart:convert-patch/convert_patch.dart:1261:9)
E/flutter (14133): #2      _ChunkedJsonParser.parse  (dart:convert-patch/convert_patch.dart:926:22)
E/flutter (14133): #3      _parseJson  (dart:convert-patch/convert_patch.dart:31:10)
E/flutter (14133): #4      JsonDecoder.convert  (dart:convert/json.dart:505:36)
E/flutter (14133): #5      JsonCodec.decode  (dart:convert/json.dart:153:41)
E/flutter (14133): #6      FlutterInsta.getProfileData 
package:flutter_insta/flutter_insta.dart:24
E/flutter (14133): <asynchronous suspension>
E/flutter (14133): #7      UserProvider.getData 
package:instaInfluence/Provider/user.dart:210
E/flutter (14133): #8      _MainHomeState.completingVerification 
package:instaInfluence/Screens/MainHome.dart:84
E/flutter (14133): #9      _MainHomeState.didChangeDependencies.<anonymous closure> 
package:instaInfluence/Screens/MainHome.dart:55
E/flutter (14133): #10     _rootRunUnary  (dart:async/zone.dart:1192:38)
E/flutter (14133): #11     _CustomZone.runUnary  (dart:async/zone.dart:1085:19)
E/flutter (14133): #12     _FutureListener.handleValue  (dart:async/future_impl.dart:141:18)
Future._propagateToListeners.handleValueCallback  (dart:async/future_impl.dart:682:45)
E/flutter (14133): #14     Future._propagateToListeners  (dart:async/future_impl.dart:711:32)
E/flutter (14133): #15     Future._completeWithValue  (dart:async/future_impl.dart:526:5)
E/flutter (14133): #16     _AsyncAwaitCompleter.complete  (dart:async-patch/async_patch.dart:36:15)
E/flutter (14133): #17     _completeOnAsyncReturn  (dart:async-patch/async_patch.dart:298:13)
E/flutter (14133): #18     _MainHomeState.getAllInfluecers (package:instaInfluence/Screens/MainHome.dart)
E/flutter (14133): <asynchronous suspension>
E/flutter (14133): #19     _MainHomeState.didChangeDependencies.<anonymous closure> 
package:instaInfluence/Screens/MainHome.dart:54
E/flutter (14133): #20     _rootRunUnary  (dart:async/zone.dart:1192:38)
E/flutter (14133): #21     _CustomZone.runUnary  (dart:async/zone.dart:1085:19)
E/flutter (14133): #22     _FutureListener.handleValue  (dart:async/future_impl.dart:141:18)
E/flutter (14133): #23     Future._propagateToListeners.handleValueCallback  (dart:async/future_impl.dart:682:45)
E/flutter (14133): #24     Future._propagateToListeners  (dart:async/future_impl.dart:711:32)
E/flutter (14133): #25     Future._completeWithValue  (dart:async/future_impl.dart:526:5)
E/flutter (14133): #26     _AsyncAwaitCompleter.complete  (dart:async-patch/async_patch.dart:36:15)
E/flutter (14133): #27     _completeOnAsyncReturn  (dart:async-patch/async_patch.dart:298:13)
E/flutter (14133): #28     _MainHomeState.getRequstStatus (package:instaInfluence/Screens/MainHome.dart)
E/flutter (14133): <asynchronous suspension>
E/flutter (14133): #29     _MainHomeState.didChangeDependencies 
package:instaInfluence/Screens/MainHome.dart:54
E/flutter (14133): #30     StatefulElement._firstBuild 
package:flutter/…/widgets/framework.dart:4661
E/flutter (14133): #31     ComponentElement.mount 
package:flutter/…/widgets/framework.dart:4476
E/flutter (14133): #32     Element.inflateWidget 
package:flutter/…/widgets/framework.dart:3446
E/flutter (14133): #33     Element.updateChild 
package:flutter/…/widgets/framework.dart:3214
E/flutter (14133): #34     ComponentElement.performRebuild 
package:flutter/…/widgets/framework.dart:4527

**Comment by codingstark-dev** [comment]
I fixed that bug wait a minute to accept my pull request

> [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: FormatException: Unexpected character (at character 1)
> E/flutter (14133):
> E/flutter (14133): ^
> E/flutter (14133):
> E/flutter (14133): #0 _ChunkedJsonParser.fail (dart:convert-patch/convert_patch.dart:1394:5)
> E/flutter (14133): #1 _ChunkedJsonParser.parseNumber (dart:convert-patch/convert_patch.dart:1261:9)
> E/flutter (14133): #2 _ChunkedJsonParser.parse (dart:convert-patch/convert_patch.dart:926:22)
> E/flutter (14133): #3 _parseJson (dart:convert-patch/convert_patch.dart:31:10)
> E/flutter (14133): #4 JsonDecoder.convert (dart:convert/json.dart:505:36)
> E/flutter (14133): #5 JsonCodec.decode (dart:convert/json.dart:153:41)
> E/flutter (14133): #6 FlutterInsta.getProfileData
> package:flutter_insta/flutter_insta.dart:24
> E/flutter (14133):
> E/flutter (14133): #7 UserProvider.getData
> package:instaInfluence/Provider/user.dart:210
> E/flutter (14133): #8 _MainHomeState.completingVerification
> package:instaInfluence/Screens/MainHome.dart:84
> E/flutter (14133): #9 _MainHomeState.didChangeDependencies.
> package:instaInfluence/Screens/MainHome.dart:55
> E/flutter (14133): #10 _rootRunUnary (dart:async/zone.dart:1192:38)
> E/flutter (14133): #11 _CustomZone.runUnary (dart:async/zone.dart:1085:19)
> E/flutter (14133): #12 _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
> Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
> E/flutter (14133): #14 Future._propagateToListeners (dart:async/future_impl.dart:711:32)
> E/flutter (14133): #15 Future._completeWithValue (dart:async/future_impl.dart:526:5)
> E/flutter (14133): #16 _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:36:15)
> E/flutter (14133): #17 _completeOnAsyncReturn (dart:async-patch/async_patch.dart:298:13)
> E/flutter (14133): #18 _MainHomeState.getAllInfluecers (package:instaInfluence/Screens/MainHome.dart)
> E/flutter (14133):
> E/flutter (14133): #19 _MainHomeState.didChangeDependencies.
> package:instaInfluence/Screens/MainHome.dart:54
> E/flutter (14133): #20 _rootRunUnary (dart:async/zone.dart:1192:38)
> E/flutter (14133): #21 _CustomZone.runUnary (dart:async/zone.dart:1085:19)
> E/flutter (14133): #22 _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
> E/flutter (14133): #23 Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
> E/flutter (14133): #24 Future._propagateToListeners (dart:async/future_impl.dart:711:32)
> E/flutter (14133): #25 Future._completeWithValue (dart:async/future_impl.dart:526:5)
> E/flutter (14133): #26 _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:36:15)
> E/flutter (14133): #27 _completeOnAsyncReturn (dart:async-patch/async_patch.dart:298:13)
> E/flutter (14133): #28 _MainHomeState.getRequstStatus (package:instaInfluence/Screens/MainHome.dart)
> E/flutter (14133):
> E/flutter (14133): #29 _MainHomeState.didChangeDependencies
> package:instaInfluence/Screens/MainHome.dart:54
> E/flutter (14133): #30 StatefulElement._firstBuild
> package:flutter/…/widgets/framework.dart:4661
> E/flutter (14133): #31 ComponentElement.mount
> package:flutter/…/widgets/framework.dart:4476
> E/flutter (14133): #32 Element.inflateWidget
> package:flutter/…/widgets/framework.dart:3446
> E/flutter (14133): #33 Element.updateChild
> package:flutter/…/widgets/framework.dart:3214
> E/flutter (14133): #34 ComponentElement.performRebuild
> package:flutter/…/widgets/framework.dart:4527
