### ISSUE TITLE
FormatException: Unexpected character (at character 1)

### ISSUE THREAD

**Issue by deveshgarg-max** [viralvaghela/flutter_insta#7]
**Still getting an error after the pull requests** its a very important project for me I can make you a collaborator on my GitHub repository there you can **solve it, please!**

`[ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: FormatException: Unexpected character (at character 1)
E/flutter (24926): <!DOCTYPE html>
E/flutter (24926): ^
E/flutter (24926):
E/flutter (24926): #0      _ChunkedJsonParser.fail  (dart:convert-patch/convert_patch.dart:1394:5)
E/flutter (24926): #1      _ChunkedJsonParser.parseNumber  (dart:convert-patch/convert_patch.dart:1261:9)
E/flutter (24926): #2      _ChunkedJsonParser.parse  (dart:convert-patch/convert_patch.dart:926:22)
E/flutter (24926): #3      _parseJson  (dart:convert-patch/convert_patch.dart:31:10)
E/flutter (24926): #4      JsonDecoder.convert  (dart:convert/json.dart:505:36)
E/flutter (24926): #5      JsonCodec.decode  (dart:convert/json.dart:153:41)
E/flutter (24926): #6      FlutterInsta.getProfileData 
package:flutter_insta/flutter_insta.dart:25
E/flutter (24926): <asynchronous suspension>
E/flutter (24926): #7      _HomePageState.printDetails 
package:flutter_insta_example/main.dart:85
E/flutter (24926): #8      _HomePageState.homePage.<anonymous closure> 
package:flutter_insta_example/main.dart:111
E/flutter (24926): #9      _InkResponseState._handleTap 
package:flutter/…/material/ink_well.dart:779
E/flutter (24926): #10     _InkResponseState.build.<anonymous closure> 
package:flutter/…/material/ink_well.dart:862
E/flutter (24926): #11     GestureRecognizer.invokeCallback 
package:flutter/…/gestures/recognizer.dart:182
E/flutter (24926): #12     TapGestureRecognizer.handleTapUp 
package:flutter/…/gestures/tap.dart:504
E/flutter (24926): #13     BaseTapGestureRecognizer._checkUp 
package:flutter/…/gestures/tap.dart:282
E/flutter (24926): #14     BaseTapGestureRecognizer.acceptGesture 
package:flutter/…/gestures/tap.dart:254
E/flutter (24926): #15     GestureArenaManager.sweep 
package:flutter/…/gestures/arena.dart:156
E/flutter (24926): #16     GestureBinding.handleEvent 
package:flutter/…/gestures/binding.dart:222
E/flutter (24926): #17     GestureBinding.dispatchEvent 
package:flutter/…/gestures/binding.dart:198
E/flutter (24926): #18     GestureBinding._handlePointerEvent `

**Comment by codingstark-dev** [comment]
> **Still getting an error after the pull requests** its a very important project for me I can make you a collaborator on my GitHub repository there you can **solve it, please!**
> 
> `[ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: FormatException: Unexpected character (at character 1) E/flutter (24926): <!DOCTYPE html> E/flutter (24926): ^ E/flutter (24926): E/flutter (24926): #0 _ChunkedJsonParser.fail (dart:convert-patch/convert_patch.dart:1394:5) E/flutter (24926): #1 _ChunkedJsonParser.parseNumber (dart:convert-patch/convert_patch.dart:1261:9) E/flutter (24926): #2 _ChunkedJsonParser.parse (dart:convert-patch/convert_patch.dart:926:22) E/flutter (24926): #3 _parseJson (dart:convert-patch/convert_patch.dart:31:10) E/flutter (24926): #4 JsonDecoder.convert (dart:convert/json.dart:505:36) E/flutter (24926): #5 JsonCodec.decode (dart:convert/json.dart:153:41) E/flutter (24926): #6 FlutterInsta.getProfileData package:flutter_insta/flutter_insta.dart:25 E/flutter (24926): <asynchronous suspension> E/flutter (24926): #7 _HomePageState.printDetails package:flutter_insta_example/main.dart:85 E/flutter (24926): #8 _HomePageState.homePage.<anonymous closure> package:flutter_insta_example/main.dart:111 E/flutter (24926): #9 _InkResponseState._handleTap package:flutter/…/material/ink_well.dart:779 E/flutter (24926): #10 _InkResponseState.build.<anonymous closure> package:flutter/…/material/ink_well.dart:862 E/flutter (24926): #11 GestureRecognizer.invokeCallback package:flutter/…/gestures/recognizer.dart:182 E/flutter (24926): #12 TapGestureRecognizer.handleTapUp package:flutter/…/gestures/tap.dart:504 E/flutter (24926): #13 BaseTapGestureRecognizer._checkUp package:flutter/…/gestures/tap.dart:282 E/flutter (24926): #14 BaseTapGestureRecognizer.acceptGesture package:flutter/…/gestures/tap.dart:254 E/flutter (24926): #15 GestureArenaManager.sweep package:flutter/…/gestures/arena.dart:156 E/flutter (24926): #16 GestureBinding.handleEvent package:flutter/…/gestures/binding.dart:222 E/flutter (24926): #17 GestureBinding.dispatchEvent package:flutter/…/gestures/binding.dart:198 E/flutter (24926): #18 GestureBinding._handlePointerEvent `

please update your dependency https://pub.dev/packages/flutter_insta , latest version is  flutter_insta: ^0.1.2

**Comment by codingstark-dev** [comment]
![Screenshot (163)](https://user-images.githubusercontent.com/40685364/90131006-060d1480-dd89-11ea-9fae-f997e8ded822.png)
My project is working well look this image.

> **Still getting an error after the pull requests** its a very important project for me I can make you a collaborator on my GitHub repository there you can **solve it, please!**
> 
> `[ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: FormatException: Unexpected character (at character 1) E/flutter (24926): <!DOCTYPE html> E/flutter (24926): ^ E/flutter (24926): E/flutter (24926): #0 _ChunkedJsonParser.fail (dart:convert-patch/convert_patch.dart:1394:5) E/flutter (24926): #1 _ChunkedJsonParser.parseNumber (dart:convert-patch/convert_patch.dart:1261:9) E/flutter (24926): #2 _ChunkedJsonParser.parse (dart:convert-patch/convert_patch.dart:926:22) E/flutter (24926): #3 _parseJson (dart:convert-patch/convert_patch.dart:31:10) E/flutter (24926): #4 JsonDecoder.convert (dart:convert/json.dart:505:36) E/flutter (24926): #5 JsonCodec.decode (dart:convert/json.dart:153:41) E/flutter (24926): #6 FlutterInsta.getProfileData package:flutter_insta/flutter_insta.dart:25 E/flutter (24926): <asynchronous suspension> E/flutter (24926): #7 _HomePageState.printDetails package:flutter_insta_example/main.dart:85 E/flutter (24926): #8 _HomePageState.homePage.<anonymous closure> package:flutter_insta_example/main.dart:111 E/flutter (24926): #9 _InkResponseState._handleTap package:flutter/…/material/ink_well.dart:779 E/flutter (24926): #10 _InkResponseState.build.<anonymous closure> package:flutter/…/material/ink_well.dart:862 E/flutter (24926): #11 GestureRecognizer.invokeCallback package:flutter/…/gestures/recognizer.dart:182 E/flutter (24926): #12 TapGestureRecognizer.handleTapUp package:flutter/…/gestures/tap.dart:504 E/flutter (24926): #13 BaseTapGestureRecognizer._checkUp package:flutter/…/gestures/tap.dart:282 E/flutter (24926): #14 BaseTapGestureRecognizer.acceptGesture package:flutter/…/gestures/tap.dart:254 E/flutter (24926): #15 GestureArenaManager.sweep package:flutter/…/gestures/arena.dart:156 E/flutter (24926): #16 GestureBinding.handleEvent package:flutter/…/gestures/binding.dart:222 E/flutter (24926): #17 GestureBinding.dispatchEvent package:flutter/…/gestures/binding.dart:198 E/flutter (24926): #18 GestureBinding._handlePointerEvent `

**Comment by viralvaghela** [comment]
@deveshgarg-max can you show which URL are you writing there? @refoxdev has fixed it and now it's working fine

**Comment by codingstark-dev** [comment]
> @deveshgarg-max can you show which URL are you writing there? @refoxdev has fixed it and now it's working fine

Yep! right bro!

**Comment by deveshgarg-max** [comment]
Hey, Actually this error is not coming from **downloadReels()** it is coming from **getProfileData()** I am using it from 10 days but this morning only I start facing this issue I checked my code there is no issue from my side

**Comment by codingstark-dev** [comment]
> Hey, Actually this error is not coming from **downloadReels()** it is coming from **getProfileData()** I am using it from 10 days but this morning only I start facing this issue I checked my code there is no issue from my side

ooh okay! let me check.

**Comment by deveshgarg-max** [comment]
hey, @refoxdev I made you a collaborator on my GitHub repository it is a humble request to have a look on user.dart file existing on Provider folder and there is one function named **getData()** there I have used this package

**Comment by codingstark-dev** [comment]
> hey, @refoxdev I made you a collaborator on my GitHub repository it is a humble request to have a look on user.dart file existing on Provider folder and there is one function named **getData()** there I have used this package

ok bro!

**Comment by codingstark-dev** [comment]
@deveshgarg-max I changed some file and now i am going to pull request check it working or not! Done!!

**Comment by deveshgarg-max** [comment]
Yes its working fine thanks flutter_insta team

**Comment by codingstark-dev** [comment]
> Yes its working fine thanks flutter_insta team

Your Welcome!

**Comment by deveshgarg-max** [comment]
Sorry But still getting the same error

**Comment by deveshgarg-max** [comment]
![Capturess](https://user-images.githubusercontent.com/53038326/90142372-e8947680-dd99-11ea-9f19-436cb2e3f63a.JPG)

**Comment by codingstark-dev** [comment]
> ![Capturess](https://user-images.githubusercontent.com/53038326/90142372-e8947680-dd99-11ea-9f19-436cb2e3f63a.JPG)
> 

Please share _username url format

**Comment by deveshgarg-max** [comment]
Hey, _username is a String which caries Instagram user name 'abcd' and to assure that my code is correct i just used your repository example and that is also facing same problems

**Comment by refoxdev** [comment]
> Hey, _username is a String which caries Instagram user name 'abcd' and to assure that my code is correct i just used your repository example and that is also facing same problems

I figured out what's the problem and now I am fixing that problem

**Comment by deveshgarg-max** [comment]
Please flutter_insta I really need this package please solve it as soon as possible

**Comment by viralvaghela** [comment]
Are you typing URL of user ? Or just a name ?

**Comment by deveshgarg-max** [comment]
just a name as per given in your example...if it is wrong please suggest me

**Comment by deveshgarg-max** [comment]
![Captsure](https://user-images.githubusercontent.com/53038326/90208358-49f22f00-de06-11ea-833c-9aa6f35407af.JPG)

**Comment by viralvaghela** [comment]
Does that username available on Instagram? which username are you writing there?

**Comment by deveshgarg-max** [comment]
for example, my Instagram username is "____no_body._ " so I'm sending this as an argument and yes before sending it I'm checking that it exists

**Comment by codingstark-dev** [comment]
> for example, my Instagram username is "____no_body._ " so I'm sending this as an argument and yes before sending it I'm checking that it exists

From where you getting user username? Firebase ?

**Comment by deveshgarg-max** [comment]
user adding it manually in the text field

**Comment by codingstark-dev** [comment]
> user adding it manually in the text field

Okay let me check

**Comment by gauravmehta13** [comment]
![image](https://user-images.githubusercontent.com/51997260/91833019-c046bc00-ec63-11ea-89d3-1ff9e454e405.png)
Unhandled Exception: FormatException: Unexpected character (at character 1)

**Comment by gauravmehta13** [comment]
https://www.instagram.com/p/CElIR8PlNdC/?igshid=77r2r50zp7w4 using this url

**Comment by thevishvajeet** [comment]
hello any update im too facing this issue

**Comment by deveshgarg-max** [comment]
hey @thevishvajeet Instagram updated its policy that's why you are facing this issue there are two solid rock solution to this problem
1. Use rest API in a limited way so that you won't get any errors(if you will do so many requests then this error will come).
2. Use authorized API from the Facebook developer console.
    How to do that?
the answer is first to create your developer console on Facebook add your application follow the steps and authorize your app with Facebook first then you need to request Facebook to give you Instagram information in JSON format and that you can use this is the official solution of this problem.
for more information visit to Facebook developer console official docs are always your friend.

**This is not a problem in the package, the package is fine but policies are changed now closing this issue.**
Thanks.
