### ISSUE TITLE
Download gets failed after starting

### ISSUE THREAD

**Issue by gauravmehta13** [viralvaghela/flutter_insta#8]
![image](https://user-images.githubusercontent.com/51997260/91835664-4fa19e80-ec67-11ea-91db-a32696c37950.png)

**Comment by gauravmehta13** [comment]
(Maybe due to insufficient permissions) How to give permissions

**Comment by viralvaghela** [comment]
Hi @gauravmehta13 ,please provide which URL you are writing in the input box.

**Comment by gauravmehta13** [comment]
https://www.instagram.com/reel/CEs4sWrAfSQ/?igshid=bidr68wbmr8d

**Comment by viralvaghela** [comment]
> https://www.instagram.com/reel/CEs4sWrAfSQ/?igshid=bidr68wbmr8d
it's working fine, make sure you have given storage permission in settings.

**Comment by gauravmehta13** [comment]
Yes i did

**Comment by viralvaghela** [comment]
Please provide **flutter run --verbose**

**Comment by viralvaghela** [comment]
No response
